#! /usr/bin/python3

import re, subprocess, sys 

manual_path = "/home/howlin/workspace/gits/manual/"
flag = re.compile(r'^\-')

docker = 'tools/docker.md'
git    = 'tools/git.md'
vim    = 'tools/vim.md'

tags = {'docker': docker, 'git': git, 'vim': vim}


def open_page(page_path):
    command = manual_path + page_path
    subprocess.call(['vim', command])


if flag.search(sys.argv[1]):
    # Call a flag function here...
    print("Call a flag function")
    
elif len(sys.argv) < 3:
    tag = sys.argv[1]
    page_path = str(tags.get(tag, 0))

    open_page(page_path)

else:
    print('Whoops. Try again.')
